### PR TITLE
Change GoDot to Godot

### PR DESCRIPTION
**Pull request by PandoCyclone**
:(

### CODE REVIEW

**Comment by GeorgeS2019** [comment]
Can you elaborate on the purpose of this PR?

**Comment by GeorgeS2019** [comment]
Can you share if this PR works with VS2022 (which version u use) and Godot4 dotnet6 after merging?

**Comment by GeorgeS2019** [comment]
Please include support for 
# VS2022!

**Comment by PandoCyclone** [comment]
I shared it in this https://github.com/godotengine/godot-csharp-visualstudio/issues/36 so try it out

**Comment by GeorgeS2019** [comment]
YES; now it install to VS2022

**Comment by GeorgeS2019** [comment]
@PandoCyclone  why u close it?

**Comment by GeorgeS2019** [comment]
@PandoCyclone  please follow [this ](https://github.com/godotengine/godot-csharp-visualstudio/issues/33#issuecomment-1233636438)and re-open your PR

**Pull request closed without merging**
