### PR TITLE
Add formatting script for GitHub Actions and add GitHub metadata

### PR DESCRIPTION
**Pull request by aaronfranke**
Follow-up to #1. The formatting script is `format.sh`, and the file which causes it to be ran automatically on GitHub Actions is
`.github/workflows/ci.yml`. The metadata mentioned in the title includes issue templates and funding information.

The CI won't run until it's in the repository, so there is no CI check for this PR itself.

### CODE REVIEW

**Comment by neikeq** [comment]
Does the script check all the files in the repo or only the files that were changed? I don't think the former is a very good idea. The [clang-format script](https://github.com/godotengine/godot/blob/master/misc/travis/clang-format.sh) does the latter.

**Comment by aaronfranke** [comment]
It checks all files in the repo, and personally I prefer it this way. If the existing files in the repo have formatting issues, I think it's best to "be noisy" about that so it gets fixed soon. If the existing files in the repo are fine, then the check still passes.

**Comment by neikeq** [comment]
Is the check passing for the current master branch?

**Comment by aaronfranke** [comment]
No, but this PR passes, so the master branch will pass once this PR is merged.

It's the same with the other PRs I submitted to the [mono team repos](https://github.com/orgs/godotengine/teams/mono/repositories). I double checked:

```
$ cd workspace/godot-mono-builds/
$ ./format.sh 
Files in this commit comply with the formatting rules.
$ cd ../godot-monodevelop-addin/
$ ./format.sh 
Files in this commit comply with the formatting rules.
$ cd ../godot-csharp-vscode/
$ ./format.sh 
Files in this commit comply with the formatting rules.
$ cd ../godot-csharp-visualstudio/
$ ./format.sh 
Files in this commit comply with the formatting rules.

```

**Comment by neikeq** [comment]
Thanks!

**Pull request merged**
