### PR TITLE
Add a menu for launching GoDot from visual studio

### PR DESCRIPTION
**Pull request by Jiiks**

### CODE REVIEW

**Comment by PandoCyclone** [comment]
I think this is cool

**Comment by PandoCyclone** [comment]
I have some suggestions

image

This Launch make it Godot cuz it is Godot not GoDot :)
And you can add a godot icon for the Godot button

image

Replace the debug with your launch button with the start icon
Or place a Godot button next to the live share button cuz it is more efficient

**Comment by PandoCyclone** [comment]
> I have some suggestions
> 
> image
> 
> This Launch make it Godot cuz it is Godot not GoDot :) And you can add a godot icon for the Godot button
> 
> image
> 
> Replace the debug button(the one that have C# text thingy) with your launch button with the start icon(**‣**) Or place a Godot button next to the live share button cuz it is more efficient
> 
> And btw what is the use of the configure button

If you think this is wierd then I'm very sorry

**Comment by GeorgeS2019** [comment]
@Jiiks 
It is **GoDot** to you but **Godot** for the rest of us.  :-)

**Comment by GeorgeS2019** [comment]
Can you share if this PR works with VS2022 (which version u use) and Godot4 dotnet6 after merging?

**Comment by PandoCyclone** [comment]
> Can you share if this PR works with VS2022 (which version u use) and Godot4 dotnet6 after merging?

idk what is PR but i tried to compile (idk is compile is correct) the plugin and it work yes :-)

**Comment by GeorgeS2019** [comment]
@Jiiks  Is this restricted to VS2019, could this be upgraded to support VS2022?

**Comment by PandoCyclone** [comment]
> @Jiiks Is this restricted to VS2019, could this be upgraded to support VS2022?

It does support vs 2022 or i mean it ONLY support 2022

**Comment by GeorgeS2019** [comment]
Unless I did the merge wrongly, I could not install to VS2019

If you are sure this is working, please share screenshots and if possible..gift...

We will ask neikeq to merge these recent PR.

**Comment by PandoCyclone** [comment]
> Unless I did the merge wrongly, I could ONLY install to VS2019
> 
> If you are sure this is working, please share screenshots and if possible..gift...
> 
> We will ask neikeq to merge these recent PR.

I sent in https://github.com/godotengine/godot-csharp-visualstudio/issues/36 so if anyone else see this try check there

**Comment by neikeq** [comment]
I hid some comments because this was turning too spammy and off-topic. Those things can be talked somewhere else.

I'll give this a review tonight. The commands solutions is one I was not fond of, but since the plugin hasn't been working for a long time, we may as well accept it's the only option for now.

**Comment by GeorgeS2019** [comment]
> we may as well accept it's the only option for now.
Great, keep the iteration AND community interest and support moving forwards!

**Comment by GeorgeS2019** [comment]
@neikeq 
If possible, please look into the closed PR ([35](https://github.com/godotengine/godot-csharp-visualstudio/pull/35)), perhaps there is something useful to add to PR(32)

I believe this was closed perhaps there is a concern that there is lack of interest of PR(35)

**Comment by neikeq** [comment]
That PR only seems to cherry-pick commits from this and another PR. I don't understand why.

**Comment by GeorgeS2019** [comment]
I think the person who submitted PR (35) has a strong **enthusiasm** for the **UI aspect** of **Godot Visual Studio Extension**.

I hope the community encourages him to continue the **UI** iteration (**at least**).

**Review by neikeq — APPROVED** [review]
Some nitpicks: `GoDot` should be changed to `Godot`. Also, we probably want a more specific id than `MyMenuGroup`.
Other than that, the changes look good. I'll wait some days in case OP wants to address the nitpicks, otherwise I'll merge.

**Comment by PandoCyclone** [comment]
> I have some suggestions
> 
> image
> 
> This Launch make it Godot cuz it is Godot not GoDot :) And you can add the Godot icon for the Godot menu and its Launch button And make the launch button save the current scene before launch?
> 
> image
> 
> You can replace the debug button(the one that have C# text thingy) with your launch button with the Godot Engine icon Edit: I found a workaround for have launch with Godot in tool bar but there is no icon there so adding Godot Engine icon might look great
> 
> image
> 
> Or place a Godot button next to the live share button cuz it is more efficient
> 
> And btw what is the use of the configure button

Btw make these so we can launch the game better cuz some of the feature is weird like why not make the button on tool bar and more stuff

**Comment by GeorgeS2019** [comment]
@PandoCyclone  Do keep up with your enthusiasm. 

I am gathering all the necessary overview and feedback. Keep it UP!

**Comment by GeorgeS2019** [comment]
<details>
<summary>Improve UI  of Godot VS Extension<summary>

## UI
e.g. Add submenu and more commands and configurations for these commands
[GodotPackage.vsct](https://github.com/godotengine/godot-csharp-visualstudio/blob/master/GodotAddinVS/GodotPackage.vsct)

## Commands
- [Commands/CommandResetGodot.cs](https://github.com/godotengine/godot-csharp-visualstudio/pull/32/files#diff-fab1e92072bbdb3233f5daf700a17ab2899726eab468dc1bac3e67ad853f0b1b)
- [Commands/CommandRunGodot.cs](https://github.com/godotengine/godot-csharp-visualstudio/pull/32/files#diff-d40d487a7dfb646cf23118d883dc2327b598a58b5b658677ace1cabe8ad58acf)

> Initialize these commands in [GodotPackage.cs](https://github.com/godotengine/godot-csharp-visualstudio/pull/32/files#diff-51ebcda1801b1484df6e9a723d28ea21fdc7a505d81417a92f963ced02e0f361)
</details>

**Comment by GeorgeS2019** [comment]
@PandoCyclone 

I assume you have added addition UI in the [GodotPackage.vsct](https://github.com/godotengine/godot-csharp-visualstudio/blob/master/GodotAddinVS/GodotPackage.vsct). 
Can you list them from your [PR;  Change GoDot to Godot](https://github.com/godotengine/godot-csharp-visualstudio/pull/35)

**Comment by neikeq** [comment]
@GeorgeS2019 Please, don't have these discussions here. None of that seems relevant to this PR, so it feels like spam.

**Comment by neikeq** [comment]
Thanks for the contribution!

If anyone wants to further improve this or fix typos, feels free to open a PR.

**Pull request merged**
