### PR TITLE
Fix can't compile plugin

### PR DESCRIPTION
**Pull request by Intrivus**
My changes from GoDot to Godot cause a problem and I fixed it

### CODE REVIEW

**Comment by PandoCyclone** [comment]
Idk why github marked it as failure but i compiled successfully

**Comment by neikeq** [comment]
There are some changes here that already seem to be on master. Can you rebase your branch to include only the new changes? Is it only the `Fix can't compile the plugin` commit?

**Comment by PandoCyclone** [comment]
> There are some changes here that already seem to be on master. Can you rebase your branch to include only the new changes? Is it only the `Fix can't compile the plugin` commit?

how?

**Comment by Commander-Firestrike** [comment]
> how?

Checkout your `GuiChanges` branch at your latest commit (`3c7f042`), then run `git rebase -i HEAD~2`. This will open a text editor. Where it says `pick 3c7f042`, change `pick` to `squash`. The whole file should like something like this:
```
squash 3c7f042 Fix can't compile the plugin
pick 17cc3a8 Changing GoDot to Godot
```
Save the file and close the text editor. Git will then open another text editor, and here you can leave everything as it is - this is just what the new commit message will be. Close the text editor. After that, your console should read `Successfully rebased and updated`. Push the branch and you should be done!

**Comment by PandoCyclone** [comment]
> > how?
> 
> Checkout your `GuiChanges` branch at your latest commit (`3c7f042`), then run `git rebase -i HEAD~2`. This will open a text editor. Where it says `pick 3c7f042`, change `pick` to `squash`. The whole file should like something like this:
> 
> ```
> squash 3c7f042 Fix can't compile the plugin
> pick 17cc3a8 Changing GoDot to Godot
> ```
> 
> Save the file and close the text editor. Git will then open another text editor, and here you can leave everything as it is - this is just what the new commit message will be. Close the text editor. After that, your console should read `Successfully rebased and updated`. Push the branch and you should be done!

how to run

**Comment by PandoCyclone** [comment]
> git rebase -i HEAD~2

how to run git rebase -i HEAD~2

**Comment by Commander-Firestrike** [comment]
> how to run git rebase -i HEAD~2

How do you push to Github? Are you using something like VSCode or Visual Studio?

**Comment by neikeq** [comment]
There can be many ways to do this. I suggest familiarizing yourself with git rebase.
What commit has the new changes? Is it the `Fix can't compile the plugin` commit only? If so you could use `git cherry-pick 3c7f042a69e4a6775075c7a256b7912b8001203e` from a new branch.
In the worst case, since it's only a few line changes, you could manually redo this from a new branch.

**Comment by Commander-Firestrike** [comment]
> you could manually redo this from a new branch.

I think this is the easiest option if Pando is unfamiliar with the git cli.

**Comment by PandoCyclone** [comment]
> > you could manually redo this from a new branch.
> 
> I think this is the easiest option if Pando is unfamiliar with the git cli.

Yes :(

**Comment by Commander-Firestrike** [comment]
> Yes :(

If you want, you could add me as a contributor to your repository and I can do the fix for you.

**Comment by PandoCyclone** [comment]
> > Yes :(
> 
> If you want, you could add me as a contributor to your repository and I can do the fix for you.

oki

**Comment by Commander-Firestrike** [comment]
Thanks! There we go, that should be fixed now! :)

**Comment by PandoCyclone** [comment]
TSYM! :)

**Comment by Commander-Firestrike** [comment]
Ok. Some strange invisible characters managed to sneak into some of the files, upsetting the formatting rules. I believe they are all fixed now, as [the latest Continuous Integration action in Pando's repo has succeeded.](https://github.com/PandoCyclone/godot-csharp-visualstudio/actions/runs/3042728497)

**Comment by Commander-Firestrike** [comment]
Also it might be a good idea to rename this PR something like "Fixing typos"

**Comment by neikeq** [comment]
Thanks!

**Pull request merged**
